name: Test Action

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - run: pip install scanoss[fast_winnowing] scancode-toolkit

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: cat "${{ steps.test-action.outputs.result-filepath }}"
